title: "Citizen Science, Citizen History"
description: ALL active citizen scientist and historian projects available to the public as of November 2021, including all currently-running distributed computing volunteer opportunities.
remote_theme: pmarsceill/just-the-docs
search_enabled: true
nav_sort: case_sensitive
